base_path: /nfs/scratch2/shared_image_recog_ml
weights_path: ${base_path}/weights/dinov2

# Environment Args
output_root: '../..'
pytorch_data_dir: '/pytorch-data'
submitting_to_aml: false
summarize: true
experiment_name: "exp1"

# Dataset args
dataset: ""
split: "train"
partition: 0
total_partitions: 1

# Model Args
# changing model_type to cell_interactome_dinvo2
model_type: "ci_dinov2"
activation_type: "token"

# Upsampler args
outlier_detection: True
downsampler_type: "attention"
blur_attn: True
mag_tv_weight: 0.05
mag_weight: 0.001
color_feats: true
pca_batch: 50 # reduced from 50
proj_dim: 128
max_pad: 30
use_flips: true
max_zoom: 1.8
blur_pin: 0.1
n_freqs: 30
param_type: "implicit"
use_norm: false

# Training args
steps: 2000
n_images: 100 # 3000

# No need to change
hydra:
  run:
    dir: "."
  output_subdir: ~


model:
  train: 
    weights: ${weights_path}/pretrain_care_vits/ckpt_step_59999.pth # weights: ${weights_path}/pretrained/dinov2_vitg14_reg4_pretrain_ckpt.pth
    dino:
      freeze_head: false
    ibot:
      freeze_head: false
      separate_head: false
    student:
      freeze_backbone: true
      arch: vit_small
      patch_size: 14
      drop_path_rate: 0.4
      layerscale: 1.0e-05
      drop_path_uniform: true
      qkv_bias: true
      proj_bias: true
      ffn_bias: true
      ffn_layer: swiglufused
      num_register_tokens: 4
      block_chunks: 0
      interpolate_antialias: false
      interpolate_offset: 0.1
    crops:
      global_crops_scale:
        - 0.32
        - 1.0
      local_crops_number: 8
      local_crops_scale:
        - 0.05
        - 0.32
      global_crops_size: 224 # 518
      local_crops_size: 98
  featup:
    upsampler:
      type: jbu_stack
      use_norm: true
      weights: ""

image:
  input_h: 224
  input_w: 224
  final_patch_size: 14


train:
  resume: true
  dataset_path: ${base_path}/care_llsm_518
  path_to_txt: ${train.dataset_path}/train.txt
  output_dir: ${weights_path}/${logging.name}
  search_suffix: ${search_suffix}
  max_files: 1000000
  num_workers: 50 # reduced from 175
  log_interval: 10
  load_optim: true

logging:
  project: cell-interactome
  entity: artificial-intelligence-research
  name: ${experiment_name}

seed: 0
device: "cuda:2"
TARGET_FILE_EXTENSION: ".pth"
search_suffix: "2D/**/*${TARGET_FILE_EXTENSION}"
